name: mathenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - sympy
  - cairo
  - pango
  - ffmpeg
  - pip
  - pre-commit
  - conda-forge::manim=0.19.0
