name: mathenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - sympy
  - pip
  - pre-commit
  # Documentation packages
  - sphinx
  - sphinx-rtd-theme
