name: Build and Deploy Docs

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          python-version: '3.10'

      - name: Setup conda environment
        shell: bash -l {0}
        run: |
          # Modify the setup script to skip removing existing env (doesn't exist yet)
          sed -i 's/conda env remove -n mathenv -y/# Skipping env removal in CI/' setup_conda_env.sh
          # Run the setup script
          bash setup_conda_env.sh
          # Activate the environment
          conda activate mathenv

      - name: Set Python path
        shell: bash -l {0}
        run: |
          # Make sure cline.py is importable
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Build docs
        shell: bash -l {0}
        run: |
          conda activate mathenv
          # Add current directory to Python path
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
